name: Deploy Next.js site to Pages

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: ./projeto-mc656/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./projeto-mc656

      - name: Run tests
        run: npm run test
        working-directory: ./projeto-mc656

  build:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect package manager
        id: detect-package-manager
        working-directory: ./projeto-mc656
        run: |
          if [ -f "${{ github.workspace }}/projeto-mc656/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/projeto-mc656/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
          cache-dependency-path: ./projeto-mc656/package-lock.json

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ./projeto-mc656/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('projeto-mc656/package-lock.json', 'projeto-mc656/yarn.lock', 'projeto-mc656/next.config.js', 'projeto-mc656/**/*.js', 'projeto-mc656/**/*.jsx', 'projeto-mc656/**/*.ts', 'projeto-mc656/**/*.tsx') }}-${{ hashFiles('projeto-mc656/pages/**/*', 'projeto-mc656/components/**/*', 'projeto-mc656/public/**/*') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('projeto-mc656/package-lock.json', 'projeto-mc656/yarn.lock') }}-


      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
        working-directory: ./projeto-mc656

      - name: Build with Next.js
        run: |
          ${{ steps.detect-package-manager.outputs.runner }} next build
          ${{ steps.detect-package-manager.outputs.runner }} next export
        working-directory: ./projeto-mc656

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./projeto-mc656/out

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
